[package]
name = "near-chain"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
near-chain-primitives.workspace = true
near-primitives = { workspace = true }
near-epoch-manager.workspace = true
near-store.workspace = true
